[package]
name = "cargis"
version = "0.1.0"
authors = ["mathiasmagnusson <mathiasmagnussons@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.11.13"
easy-http-request = "0.0.7"
unzip = "0.1.0"
text_io = "0.1.7"
